# Generated by Django 5.2.9 on 2026-01-09 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_comments_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to='social.socialprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['post'], name='social_post_post_id_3ab6bc_idx'), models.Index(fields=['user'], name='social_post_user_id_64779f_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
