# Generated by Django 5.2.5 on 2025-09-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes_topics', to='social.topic'),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interest_topics', to='social.topic'),
        ),
    ]
